server:
  port: 8081

spring:
  application:
    name: it-gateway

eureka:
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
    fetch-registry: true

zuul:
  routes:
    it-service: /it-service/**
    it-ip: /ip/**
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  retryable: true

ribbon:
  # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 1
  # Max number of next servers to retry (excluding the first server)
  #当允许在其他服务器上重试的时候，会调用IRule.choose选择可用服务实例中的
  #其他一台服务实例进行调用
  MaxAutoRetriesNextServer: 2
  # Whether all operations can be retried for this client
  OkToRetryOnAllOperations: true  #默认为false,则只允许GET请求被重试
  ReadTimeout: 5000
  ConnectTimeout: 2000